namespace Torino
{
	public enum ReplyCode
	{
		OK = 250,
		UNNECESSARY_OPERATION = 251,
		EXHAUSTED = 451,
		SYNTAX_ERROR = 500,
		UNRECOGNIZED_COMMAND = 510,
		UNIMPLEMENTED_COMMAND = 511,
		SYNTAX_ERROR_ARGUMENT = 512,
		UNRECOGNIZED_ARGUMENT = 513,
		AUTHENTICATION_REQUIRED = 514,
		BAD_AUTHENTICATION = 515,
		UNSPECIFIED_TOR_ERROR = 550,
		INTERNAL_ERROR = 551,
		UNRECOGNIZED_ENTITY = 552,
		INVALID_CONFIGURATION_VALUE = 553,
		INVALID_DESCRIPTOR = 554,
		UNMANAGED_ENTITY = 555,
		ASYNC_EVENT_NOTIFICATION = 650
	}

	internal enum Command
	{
		SETCONF,
		RESETCONF,
		GETCONF,
		SETEVENTS,
		AUTHENTICATE,
		SAVECONF,
		SIGNAL,
		MAPADDRESS,
		GETINFO,
		EXTENDCIRCUIT,
		SETCIRCUITPURPOSE,
		SETROUTERPURPOSE,
		ATTACHSTREAM,
		POSTDESCRIPTOR,
		REDIRECTSTREAM,
		CLOSESTREAM,
		CLOSECIRCUIT,
		QUIT,
		USEFEATURE,
		RESOLVE,
		PROTOCOLINFO,
		LOADCONF,
		TAKEOWNERSHIP,
		AUTHCHALLENGE,
		DROPGUARDS,
		HSFETCH,
		ADD_ONION,
		DEL_ONION,
		HSPOST,
		ONION_CLIENT_AUTH_ADD,
		ONION_CLIENT_AUTH_REMOVE,
		ONION_CLIENT_AUTH_VIEW,
		DROPOWNERSHIP
	}
}